# Generated by Django 5.1.7 on 2025-04-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_telegramconnectiontoken_telegramuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramconnectiontoken',
            name='token',
            field=models.CharField(default='ff45fb17b2434ab4ac4a823eb06eaf74', max_length=36, unique=True),
        ),
    ]
