# Generated by Django 5.1.7 on 2025-04-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_telegramconnectiontoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramconnectiontoken',
            name='token',
            field=models.CharField(default='c3479ee8ae0b4a3b96c64dcd596bcca0', max_length=36, unique=True),
        ),
    ]
