# Generated by Django 5.1.7 on 2025-04-10 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_telegramconnectiontoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramconnectiontoken',
            name='token',
            field=models.CharField(default='e2236ffc4afc4acbb9192c984c047ca3', max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
