# Generated by Django 5.1.7 on 2025-04-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_telegramconnectiontoken_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramconnectiontoken',
            name='token',
            field=models.CharField(default='b3bec50315454b83988ca9f149a48091', max_length=36, unique=True),
        ),
    ]
