# Generated by Django 5.1.7 on 2025-04-10 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_telegramconnectiontoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramconnectiontoken',
            name='token',
            field=models.CharField(default='a5e2df79a49d4e558c130779f374ca8a', max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='telegramconnectiontoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.telegramuser'),
        ),
    ]
