# Generated by Django 5.1.7 on 2025-04-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_telegramconnectiontoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramconnectiontoken',
            name='token',
            field=models.CharField(default='cf5ce455b58a4793be879d626d1e4360', max_length=36, unique=True),
        ),
    ]
