# Generated by Django 5.1.7 on 2025-04-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_telegramconnectiontoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramconnectiontoken',
            name='token',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
