# Generated by Django 5.1.7 on 2025-04-11 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_telegramconnectiontoken_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='TelegramConnectionToken',
        ),
        migrations.DeleteModel(
            name='TelegramUser',
        ),
    ]
