# Generated by Django 5.1.7 on 2025-03-23 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='documents_valid_until',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('IN_QUEUE', 'In Queue'), ('HOUSING_OFFERED', 'Housing Offered'), ('ACCEPTED', 'Accepted'), ('REJECTED_BY_APPLICANT', 'Rejected by Applicant'), ('REJECTED_BY_MANAGER', 'Rejected by Manager'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='applicationhistory',
            name='new_status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('IN_QUEUE', 'In Queue'), ('HOUSING_OFFERED', 'Housing Offered'), ('ACCEPTED', 'Accepted'), ('REJECTED_BY_APPLICANT', 'Rejected by Applicant'), ('REJECTED_BY_MANAGER', 'Rejected by Manager'), ('EXPIRED', 'Expired')], max_length=30),
        ),
        migrations.AlterField(
            model_name='applicationhistory',
            name='previous_status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('IN_QUEUE', 'In Queue'), ('HOUSING_OFFERED', 'Housing Offered'), ('ACCEPTED', 'Accepted'), ('REJECTED_BY_APPLICANT', 'Rejected by Applicant'), ('REJECTED_BY_MANAGER', 'Rejected by Manager'), ('EXPIRED', 'Expired')], max_length=30),
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('INCOME_STATEMENT', 'Income Statement'), ('DISABILITY_CERTIFICATE', 'Disability Certificate'), ('VETERAN_STATUS', 'Veteran Status'), ('OTHER', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='application_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('relationship', models.CharField(choices=[('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('PARENT', 'Parent'), ('SIBLING', 'Sibling'), ('OTHER', 'Other')], max_length=50)),
                ('has_disability', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_members', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('BIRTH_CERTIFICATE', 'Birth Certificate'), ('ID_PROOF', 'ID Proof'), ('DISABILITY_CERTIFICATE', 'Disability Certificate'), ('OTHER', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='household_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('household_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.householdmember')),
            ],
        ),
    ]
