# Generated by Django 5.1.7 on 2025-03-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_remove_application_documents_valid_until_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='adults_count',
        ),
        migrations.RemoveField(
            model_name='application',
            name='children_count',
        ),
        migrations.RemoveField(
            model_name='application',
            name='elderly_count',
        ),
        migrations.AlterField(
            model_name='householddocument',
            name='document_type',
            field=models.CharField(choices=[('ID_PROOF', 'ID Proof'), ('DISABILITY_CERTIFICATE', 'Disability Certificate'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
