# Generated by Django 5.1.7 on 2025-03-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_remove_application_adults_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='householdmember',
            name='application',
        ),
        migrations.RemoveField(
            model_name='application',
            name='queue_position',
        ),
        migrations.AddField(
            model_name='application',
            name='adults_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='application',
            name='children_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='elderly_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('IN_QUEUE', 'In Queue'), ('HOUSING_OFFERED', 'Housing Offered'), ('ACCEPTED', 'Accepted'), ('REJECTED_BY_APPLICANT', 'Rejected by Applicant'), ('REJECTED_BY_MANAGER', 'Rejected by Manager')], default='SUBMITTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='applicationhistory',
            name='new_status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('IN_QUEUE', 'In Queue'), ('HOUSING_OFFERED', 'Housing Offered'), ('ACCEPTED', 'Accepted'), ('REJECTED_BY_APPLICANT', 'Rejected by Applicant'), ('REJECTED_BY_MANAGER', 'Rejected by Manager')], max_length=30),
        ),
        migrations.AlterField(
            model_name='applicationhistory',
            name='previous_status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('IN_QUEUE', 'In Queue'), ('HOUSING_OFFERED', 'Housing Offered'), ('ACCEPTED', 'Accepted'), ('REJECTED_BY_APPLICANT', 'Rejected by Applicant'), ('REJECTED_BY_MANAGER', 'Rejected by Manager')], max_length=30),
        ),
        migrations.DeleteModel(
            name='HouseholdDocument',
        ),
        migrations.DeleteModel(
            name='HouseholdMember',
        ),
    ]
