# Generated by Django 5.1.7 on 2025-03-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_remove_householdmember_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdocument',
            name='document_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='document_type',
            field=models.CharField(choices=[('INCOME_STATEMENT', 'Income Statement'), ('DISABILITY_CERTIFICATE', 'Disability Certificate'), ('VETERAN_STATUS', 'Veteran Status'), ('SINGLE_PARENT_PROOF', 'Single Parent Proof'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
