# Generated by Django 5.1.7 on 2025-03-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_applicationdocument_document_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_for_ward',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicationdocument',
            name='document_type',
            field=models.CharField(choices=[('ID_PROOF', 'ID Proof'), ('INCOME_STATEMENT', 'Income Statement'), ('DISABILITY_CERTIFICATE', 'Disability Certificate'), ('VETERAN_STATUS', 'Veteran Status'), ('SINGLE_PARENT_PROOF', 'Single Parent Proof'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
