# Generated by Django 5.1.7 on 2025-04-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_application_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='document_renewal',
            field=models.BooleanField(default=False),
        ),
    ]
