# Generated by Django 5.1.7 on 2025-04-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_application_document_renewal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('IN_QUEUE', 'In Queue'), ('HOUSING_OFFERED', 'Housing Offered'), ('REJECTED_BY_MANAGER', 'Rejected by Manager')], default='SUBMITTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='applicationhistory',
            name='new_status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('IN_QUEUE', 'In Queue'), ('HOUSING_OFFERED', 'Housing Offered'), ('REJECTED_BY_MANAGER', 'Rejected by Manager')], max_length=30),
        ),
        migrations.AlterField(
            model_name='applicationhistory',
            name='previous_status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('IN_QUEUE', 'In Queue'), ('HOUSING_OFFERED', 'Housing Offered'), ('REJECTED_BY_MANAGER', 'Rejected by Manager')], max_length=30),
        ),
    ]
