# Generated by Django 5.1.7 on 2025-04-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='category',
            field=models.CharField(blank=True, choices=[('VETERAN', 'Veteran of the Great Patriotic War'), ('ORPHAN', 'Orphan or child without parental care'), ('LARGE_FAMILY', 'Large family with awards or many children'), ('SOCIAL_VULNERABLE', 'Socially vulnerable group'), ('GOVERNMENT_EMPLOYEE', 'Government employee'), ('BUDGET_WORKER', 'Budget organization worker'), ('MILITARY', 'Military personnel'), ('ASTRONAUT', 'Astronaut or candidate'), ('ELECTED_OFFICIAL', 'Elected official'), ('EMERGENCY_HOUSING', 'Citizen with emergency housing')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='has_disabled_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='has_emergency_housing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='is_orphan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='is_without_parental_care',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='large_family_awards',
            field=models.CharField(blank=True, choices=[('ALTYN_ALQA', 'Altyn alqa'), ('KUMIS_ALQA', 'Kumis alqa'), ('MOTHER_HEROINE', 'Mother heroine'), ('MATERNAL_GLORY_I', 'Maternal glory I'), ('MATERNAL_GLORY_II', 'Maternal glory II')], max_length=50, null=True),
        ),
    ]
