# Generated by Django 5.1.7 on 2025-03-17 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('floor', models.PositiveSmallIntegerField()),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rooms_count', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Under Maintenance')], default='AVAILABLE', max_length=20)),
                ('is_accessible', models.BooleanField(default=False)),
                ('has_elevator', models.BooleanField(default=False)),
                ('has_heating', models.BooleanField(default=True)),
                ('last_inspection_date', models.DateField(blank=True, null=True)),
                ('next_available_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HousingAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_date', models.DateField(auto_now_add=True)),
                ('response_deadline', models.DateField()),
                ('status', models.CharField(choices=[('OFFERED', 'Offered'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Offer Expired'), ('ACTIVE', 'Tenancy Active'), ('TERMINATED', 'Tenancy Terminated')], default='OFFERED', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('tenancy_start_date', models.DateField(blank=True, null=True)),
                ('tenancy_end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
            ],
        ),
    ]
