# Generated by Django 5.1.7 on 2025-03-27 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing_units', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housingallocation',
            name='response_deadline',
        ),
    ]
