# Generated by Django 5.1.7 on 2025-04-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_units', '0003_remove_housingallocation_response_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housingallocation',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='housingallocation',
            name='response_date',
        ),
        migrations.RemoveField(
            model_name='housingallocation',
            name='tenancy_start_date',
        ),
        migrations.AlterField(
            model_name='housingallocation',
            name='status',
            field=models.CharField(choices=[('OFFERED', 'Offered'), ('EXPIRED', 'Offer Expired'), ('ACTIVE', 'Tenancy Active')], default='OFFERED', max_length=20),
        ),
    ]
