# Generated by Django 5.1.7 on 2025-04-03 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing_units', '0004_remove_housingallocation_rejection_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housingunit',
            name='is_accessible',
        ),
    ]
