# Generated by Django 5.1.7 on 2025-04-16 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_units', '0005_remove_housingunit_is_accessible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housingunit',
            name='floor',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='housingunit',
            name='rooms_count',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
