# Generated by Django 5.1.7 on 2025-04-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('STATUS_CHANGE', 'Status Change'), ('DOCUMENT_RENEWAL', 'Document Renewal'), ('QUEUE_UPDATE', 'Queue Position Update'), ('HOUSING_OFFER', 'Housing Offer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('UNREAD', 'Unread'), ('READ', 'Read')], default='UNREAD', max_length=10),
        ),
    ]
